# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161108_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.Event'),
        ),
    ]
