# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usergroup', '0004_usergroup_admins'),
        ('users', '0006_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='usergroup.UserGroup'),
        ),
    ]
