# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_country_key_figures_data_migrations'),
        ('users', '0007_activitylog_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.Event'),
        ),
    ]
