# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0036_country_reference_country'),
        ('users', '0008_activitylog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.Country'),
        ),
    ]
