# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 10:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='attachments/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('confidentiality', models.CharField(choices=[('UNP', 'Unprotected'), ('PRO', 'Protected'), ('RES', 'Restricted'), ('CON', 'Confidential')], default='UNP', max_length=3)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('PRO', 'Processed'), ('DEL', 'Deleted')], default='PEN', max_length=3)),
                ('lead_type', models.CharField(choices=[('URL', 'Url'), ('MAN', 'Manual'), ('ATT', 'Attachments'), ('SOS', 'Survey of surveys')], default='MAN', max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.Source'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Lead'),
        ),
    ]
