# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentformat',
            name='content_format',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
