# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20160508_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.Lead'),
        ),
    ]
