# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20160430_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('URL', 'Url'), ('MAN', 'Manual')], default='MAN', max_length=3),
        ),
    ]
