# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20160802_1613'),
        ('leads', '0003_auto_20160514_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='countries',
            field=models.ManyToManyField(blank=True, to='entries.Country'),
        ),
    ]
