# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_lead_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='id',
        ),
        migrations.AlterField(
            model_name='source',
            name='source',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
