# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20161121_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
