# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 11:15
from __future__ import unicode_literals

from django.db import migrations


def migrate_source(apps, schema_editor):
    Lead = apps.get_model("leads", "Lead")
    for lead in Lead.objects.all():
        if lead.source:
            lead.source_name = lead.source.name
        lead.save()


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_source_name'),
    ]

    operations = [
        migrations.RunPython(migrate_source),
    ]
