# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20161006_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyofsurvey',
            name='data_collection_technique',
        ),
        migrations.AddField(
            model_name='surveyofsurvey',
            name='end_data_collection',
            field=models.ManyToManyField(blank=True, related_name='end_data_collections', to='leads.DataCollectionTechnique'),
        ),
        migrations.AddField(
            model_name='surveyofsurvey',
            name='start_data_collection',
            field=models.ManyToManyField(blank=True, related_name='start_data_collections', to='leads.DataCollectionTechnique'),
        ),
    ]
