# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20160501_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='content_format',
        ),
        migrations.AlterField(
            model_name='lead',
            name='confidentiality',
            field=models.CharField(choices=[('UNP', 'Unprotected'), ('PRO', 'Protected'), ('RES', 'Restricted'), ('CON', 'Confidential')], default='UNP', max_length=3),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('URL', 'Url'), ('MAN', 'Manual'), ('ATT', 'Attachments'), ('SOS', 'Survey of surveys')], default='MAN', max_length=3),
        ),
        migrations.DeleteModel(
            name='ContentFormat',
        ),
    ]
