# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-08 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20161006_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyofsurvey',
            name='data_collection_technique',
            field=models.ManyToManyField(blank=True, to='leads.DataCollectionTechnique'),
        ),
        migrations.RemoveField(
            model_name='surveyofsurvey',
            name='end_data_collection',
        ),
        migrations.AddField(
            model_name='surveyofsurvey',
            name='end_data_collection',
            field=models.DateField(default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='surveyofsurvey',
            name='start_data_collection',
        ),
        migrations.AddField(
            model_name='surveyofsurvey',
            name='start_data_collection',
            field=models.DateField(default=None, null=True),
        ),
    ]
