# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20161201_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='glide_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
