# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 06:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0007_event_glide_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assignee',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_donot_use', to=settings.AUTH_USER_MODEL, verbose_name='DO NOT USE'),
        ),
    ]
