# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-08 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_sectorcovered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyofsurvey',
            name='end_data_collection',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='surveyofsurvey',
            name='partners',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='surveyofsurvey',
            name='start_data_collection',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
