# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20161209_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='spill_over',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.Event'),
        ),
    ]
