# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-08 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20161008_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyofsurvey',
            name='affected_groups',
            field=models.TextField(default='[]'),
        ),
    ]
