# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_surveyofsurvey_affected_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectoranalyticalvalue',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sectorquantification',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
