# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_auto_20161225_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='hdi_geo_score',
        ),
        migrations.RemoveField(
            model_name='country',
            name='hdi_rank',
        ),
        migrations.RemoveField(
            model_name='country',
            name='u5m_geo_score',
        ),
        migrations.RemoveField(
            model_name='country',
            name='uprooted_geo_score',
        ),
        migrations.RemoveField(
            model_name='country',
            name='uprooted_percentage',
        ),
    ]
