# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20170104_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='number_of_idps',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='number_of_refugees',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='number_of_returned_refugees',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
