# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_auto_20170104_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='total_population',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
