# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 08:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_country_total_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 4, 8, 52, 9, 134696, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='population_source',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
