# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_auto_20170104_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='inform_final_score',
            new_name='inform_score',
        ),
    ]
