# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_auto_20170104_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplifiedLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.Lead')),
            ],
        ),
    ]
