# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_simplifiedlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(0, 'Global monitoring'), (1, 'Active crisis')], default=1),
        ),
    ]
