# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='media_sources',
            field=models.TextField(default='{}'),
        ),
    ]
