# -*- coding: utf-8 -*-
# Generated by Navin Ayer(@thenav56) with Django 1.10.5 on 2017-02-14 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import json


def forwards_func(apps, schema_editor):
    Country = apps.get_model("leads", "Country")
    db_alias = schema_editor.connection.alias
    for country in Country.objects.using(db_alias).all():
        key_figures = {
            'hdi_index': country.hdi_index,
            'hdi_rank': country.hdi_rank,
            'u5m': country.u5m,
            'number_of_refugees': country.number_of_refugees,
            'number_of_idps': country.number_of_idps,
            'number_of_returned_refugees': country.number_of_returned_refugees,
            'total_population': country.total_population,
            'population_source': country.population_source,
            'inform_score': country.inform_score,
            'inform_risk_index': country.inform_risk_index,
            'inform_hazard_and_exposure': country.inform_hazard_and_exposure,
            'inform_vulnerability': country.inform_vulnerability,
            'inform_lack_of_coping_capacity':
                country.inform_lack_of_coping_capacity,
        }

        country.key_figures = json.dumps(key_figures)

        country.save()


def reverse_func(apps, schema_editor):
    Country = apps.get_model("leads", "Country")
    db_alias = schema_editor.connection.alias
    for country in Country.objects.using(db_alias).all():
        key_figures = json.loads(country.key_figures)

        country.hdi_index = key_figures['hdi_index'],
        country.hdi_rank = key_figures['hdi_rank'],
        country.u5m = key_figures['u5m'],
        country.number_of_refugees = key_figures['number_of_refugees'],
        country.number_of_idps = key_figures['number_of_idps'],
        country.number_of_returned_refugees =\
            key_figures['number_of_returned_refugees'],
        country.total_population = key_figures['total_population'],
        country.population_source = key_figures['population_source'],
        country.inform_score = key_figures['inform_score'],
        country.inform_risk_index = key_figures['inform_risk_index'],
        country.inform_hazard_and_exposure =\
            key_figures['inform_hazard_and_exposure'],
        country.inform_vulnerability = key_figures['inform_vulnerability'],
        country.inform_lack_of_coping_capacity =\
            key_figures['inform_lack_of_coping_capacity'],

        country.save()


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_country_regions'),
    ]

    operations = [
        # Add New Field (for storing Json)
        migrations.AddField(
            model_name='country',
            name='key_figures',
            field=models.TextField(default='{}'),
        ),

        # Migrate Data to New Field
        migrations.RunPython(forwards_func, reverse_func),

        # Remove Old Field
        migrations.RemoveField(
            model_name='country',
            name='hdi_index',
        ),
        migrations.RemoveField(
            model_name='country',
            name='hdi_rank',
        ),
        migrations.RemoveField(
            model_name='country',
            name='u5m',
        ),

        migrations.RemoveField(
            model_name='country',
            name='number_of_refugees',
        ),
        migrations.RemoveField(
            model_name='country',
            name='number_of_idps',
        ),
        migrations.RemoveField(
            model_name='country',
            name='number_of_returned_refugees',
        ),

        migrations.RemoveField(
            model_name='country',
            name='total_population',
        ),
        migrations.RemoveField(
            model_name='country',
            name='population_source',
        ),

        migrations.RemoveField(
            model_name='country',
            name='inform_score',
        ),
        migrations.RemoveField(
            model_name='country',
            name='inform_risk_index',
        ),
        migrations.RemoveField(
            model_name='country',
            name='inform_hazard_and_exposure',
        ),
        migrations.RemoveField(
            model_name='country',
            name='inform_vulnerability',
        ),
        migrations.RemoveField(
            model_name='country',
            name='inform_lack_of_coping_capacity',
        ),
    ]
