# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 04:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0023_country_key_figures_data_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='events_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
