# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 05:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0025_leadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owners',
            field=models.ManyToManyField(blank=True, default=None, related_name='events_superowned', to=settings.AUTH_USER_MODEL),
        ),
    ]
