# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 05:40
from __future__ import unicode_literals

from django.db import migrations


def migrate_event_owners(app, schema_editor):
    Event = app.get_model('leads', 'Event')
    for event in Event.objects.all():
        if event.admins.count() > 0:
            event.owners.add(event.admins.all()[0])
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_event_owners'),
    ]

    operations = [
        migrations.RunPython(migrate_event_owners),
    ]
