# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_auto_20170315_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='owners',
        ),
    ]
