# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0035_auto_20170405_0548'),
        ('leads', '0028_remove_event_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entry_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.EntryTemplate'),
        ),
    ]
