# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_auto_20170502_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
