# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0032_event_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
