# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 09:49
from __future__ import unicode_literals

from django.db import migrations


def migrate_assigned_to_admins(apps, schema_editor):
    Event = apps.get_model('leads', 'Event')
    for event in Event.objects.all():
        for user in event.assignee.all():
            if user not in event.admins.all():
                event.admins.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0034_auto_20170502_0739'),
    ]

    operations = [
        migrations.RunPython(migrate_assigned_to_admins),
    ]
