# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0035_auto_20170503_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='reference_country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.Country'),
        ),
    ]
