# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 05:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0036_country_reference_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
