# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_humanprofilefield_dashboard_refugees_field'),
        ('leads', '0037_auto_20170711_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfReporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='surveyofsurvey',
            name='disaster_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.DisasterType'),
        ),
        migrations.AddField(
            model_name='surveyofsurvey',
            name='donors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyofsurvey',
            name='unit_of_reporting',
            field=models.ManyToManyField(blank=True, to='leads.UnitOfReporting'),
        ),
    ]
