# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0038_auto_20170807_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='unitofreporting',
            options={'verbose_name_plural': 'Units of Reporting'},
        ),
        migrations.AddField(
            model_name='surveyofsurvey',
            name='coordination',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.Coordination'),
        ),
    ]
