# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-08 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytimeline',
            options={'verbose_name_plural': 'Category Timelines'},
        ),
        migrations.AlterModelOptions(
            name='disastertype',
            options={'verbose_name_plural': 'Disaster Types'},
        ),
        migrations.AlterModelOptions(
            name='humanaccessfield',
            options={'verbose_name_plural': 'Humanitarian Access Fields'},
        ),
        migrations.AlterModelOptions(
            name='humanaccesspinfield',
            options={'verbose_name_plural': 'Humanitarian Access PIN Fields'},
        ),
        migrations.AlterModelOptions(
            name='humanprofilefield',
            options={'verbose_name_plural': 'Humanitarian Profile Fields'},
        ),
        migrations.AlterModelOptions(
            name='peopleinneedfield',
            options={'verbose_name_plural': 'PIN Fields'},
        ),
        migrations.AlterModelOptions(
            name='reportstatus',
            options={'verbose_name_plural': 'Report Statuses'},
        ),
        migrations.AlterModelOptions(
            name='weeklyreport',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'Weekly Reports'},
        ),
    ]
