# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-03 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20161003_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanProfileField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.HumanProfileField')),
            ],
        ),
    ]
