# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-04 14:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_humanprofilefield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyreport',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='month',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='week',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='year',
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 4, 14, 13, 45, 568205)),
            preserve_default=False,
        ),
    ]
