# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20161121_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humanprofilefield',
            options={'ordering': ['ordering'], 'verbose_name_plural': 'Humanitarian Profile Fields'},
        ),
        migrations.AddField(
            model_name='humanprofilefield',
            name='ordering',
            field=models.IntegerField(default=1),
        ),
    ]
