# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20161213_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanprofilefield',
            name='sum_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sum_children', to='report.HumanProfileField'),
        ),
    ]
