# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20161213_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanProfileFieldRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparision', models.CharField(choices=[('<', 'Less than parent'), ('+', 'Sum equal to parent'), ('+<', 'Sum equal to or less than parent')], max_length=5)),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='humanprofilefield',
        #     name='sum_to',
        # ),
        migrations.AddField(
            model_name='humanprofilefieldrule',
            name='children',
            field=models.ManyToManyField(related_name='rule_children', to='report.HumanProfileField'),
        ),
        migrations.AddField(
            model_name='humanprofilefieldrule',
            name='parent_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.HumanProfileField'),
        ),
    ]
