# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_categorytimeline_disastertype_reportstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='disastertype',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.DisasterType'),
        ),
    ]
