# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20161213_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanprofilefieldrule',
            name='comparision',
            field=models.CharField(choices=[('<', 'Less than or equal to parent'), ('+', 'Sum equal to parent'), ('+<', 'Sum equal to or less than parent')], max_length=5),
        ),
    ]
