# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20161214_0420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humanprofilefield',
            options={'ordering': ['parent__id', 'ordering'], 'verbose_name_plural': 'Humanitarian Profile Fields'},
        ),
        migrations.AlterField(
            model_name='humanprofilefieldrule',
            name='comparision',
            field=models.CharField(choices=[('<', 'Less than or equal to parent'), ('+', 'Sum equal to parent'), ('+<', 'Sum less than or equal to parent')], max_length=5),
        ),
    ]
