# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20161214_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanprofilefield',
            name='total_affected_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humanprofilefield',
            name='total_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peopleinneedfield',
            name='total_field',
            field=models.BooleanField(default=False),
        ),
    ]
