# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20161220_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyreport',
            options={'ordering': ['-start_date', '-last_edited_at'], 'verbose_name_plural': 'Weekly Reports'},
        ),
    ]
