# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-13 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20161229_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanaccesspinfield',
            name='dashboard_access_constraints_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humanprofilefield',
            name='dashboard_affected_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humanprofilefield',
            name='dashboard_availability_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peopleinneedfield',
            name='dashboard_in_need_field',
            field=models.BooleanField(default=False),
        ),
    ]
