# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20170113_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanprofilefield',
            name='dashboard_displaced_field',
            field=models.BooleanField(default=False),
        ),
    ]
