# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_humanprofilefield_dashboard_displaced_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinneedfield',
            name='dashboard_in_need_field',
            field=models.BooleanField(default=True),
        ),
    ]
