# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_auto_report_source_migrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peopleinneedfield',
            options={'ordering': ['order'], 'verbose_name_plural': 'PIN Fields'},
        ),
        migrations.AddField(
            model_name='peopleinneedfield',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
