# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 06:47
from __future__ import unicode_literals

from django.db import migrations

import json


def add_new_ill_fields(apps, schema_editor):
    HumanProfileField = apps.get_model('report', 'HumanProfileField')

    parent = None
    try:
        parent = HumanProfileField.objects.get(name__iexact='Total casualties')
    except:
        parent = None

    if HumanProfileField.objects.filter(name__iexact='Ill confirmed').count() == 0:
        try:
            ill_field = HumanProfileField.objects.get(name__iexact='Ill')
            ill_field.name = 'Ill confirmed'
            ill_field.save()
        except:
            ill_confirmed = HumanProfileField(name='Ill confirmed')
            ill_confirmed.parent = parent
            ill_confirmed.ordering = 3
            ill_confirmed.save()

    if HumanProfileField.objects.filter(name__iexact='Ill suspected').count() == 0:
        ill_suspected = HumanProfileField(name='Ill suspected')
        ill_suspected.parent = parent
        ill_suspected.ordering = 3
        ill_suspected.save()


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_humanprofilefield_tab'),
    ]

    operations = [
        migrations.RunPython(add_new_ill_fields),
    ]
