# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_humanprofilefield_dashboard_idp_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanprofilefield',
            name='dashboard_refugees_field',
            field=models.BooleanField(default=False),
        ),
    ]
