# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 15:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0003_auto_20160514_0519'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=70)),
                ('property_name', models.CharField(max_length=70)),
                ('geojson', models.FileField(upload_to='adminlevels/')),
            ],
            options={
                'ordering': ['country', 'level'],
            },
        ),
        migrations.CreateModel(
            name='AdminLevelSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('admin_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.AdminLevel')),
            ],
        ),
        migrations.CreateModel(
            name='AffectedGroup',
            fields=[
                ('name', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.AffectedGroup')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerpt', models.TextField(blank=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('reliability', models.CharField(blank=True, choices=[('COM', 'Completely'), ('USU', 'Usually'), ('FAI', 'Fairly'), ('NUS', 'Not Usually'), ('UNR', 'Unreliable'), ('CBJ', 'Cannot be judged')], default=None, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_groups', models.ManyToManyField(blank=True, to='entries.AffectedGroup')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Lead')),
                ('map_selections', models.ManyToManyField(blank=True, to='entries.AdminLevelSelection')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='InformationAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='InformationAttributeGroup',
            fields=[
                ('name', models.CharField(max_length=70, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('name', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('tags_json', models.TextField(blank=True, default='[]')),
            ],
        ),
        migrations.AddField(
            model_name='informationattribute',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.InformationAttributeGroup'),
        ),
        migrations.AddField(
            model_name='attributedata',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.InformationAttribute'),
        ),
        migrations.AddField(
            model_name='attributedata',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Entry'),
        ),
        migrations.AddField(
            model_name='adminlevel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Country'),
        ),
        migrations.AlterUniqueTogether(
            name='adminlevelselection',
            unique_together=set([('admin_level', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='adminlevel',
            unique_together=set([('country', 'level')]),
        ),
    ]
