# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='AffectedGroupData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_cases', models.IntegerField(blank=True, null=True)),
                ('affected_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.AffectedGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='CrisisDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerpt', models.TextField()),
                ('information_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('LIA', 'Living in the area'), ('AFF', 'Affected'), ('INN', 'In need'), ('TAR', 'Targeted'), ('REA', 'Reached'), ('COV', 'Covered')], default=None, max_length=3, null=True)),
                ('problem_timeline', models.CharField(blank=True, choices=[('CUR', 'Current and Confirmed Problem'), ('FUT', 'Future Problem'), ('POT', 'Potential Problem'), ('NOP', 'No Problem')], default=None, max_length=3, null=True)),
                ('severity', models.CharField(blank=True, choices=[('NOP', 'No Problem'), ('MIN', 'Minor Problem'), ('SOC', 'Situation of Concern'), ('SOM', 'Situation of Major Concern'), ('SEV', 'Severe Conditions'), ('CRI', 'Critical Situation')], default=None, max_length=3, null=True)),
                ('reliability', models.CharField(blank=True, choices=[('COM', 'Completely'), ('USU', 'Usually'), ('FAI', 'Fairly'), ('NUS', 'Not Usually'), ('UNR', 'Unreliable'), ('CBJ', 'Cannot be judged')], default=None, max_length=3, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Country')),
                ('crisis_driver', models.ManyToManyField(blank=True, to='entries.CrisisDriver')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Lead')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='VulnerableGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='VulnerableGroupData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_cases', models.IntegerField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Entry')),
                ('vulnerable_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.VulnerableGroup')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='entries.Sector'),
        ),
        migrations.AddField(
            model_name='affectedgroupdata',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Entry'),
        ),
    ]
