# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderlyingFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='underlying_factors',
            field=models.ManyToManyField(blank=True, to='entries.UnderlyingFactor'),
        ),
    ]
