# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedata',
            name='severity',
            field=models.CharField(blank=True, choices=[('NOP', 'No Problem'), ('MIN', 'Minor Problem'), ('SOC', 'Situation of Concern'), ('SOM', 'Situation of Major Concern'), ('SEV', 'Severe Conditions'), ('CRI', 'Critical Situation')], default=None, max_length=3, null=True),
        ),
    ]
