# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_attributedata_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificNeedsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VulnerableGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('min_age', models.IntegerField(blank=True, default=None, null=True)),
                ('max_age', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='sepecific_needs_groups',
            field=models.ManyToManyField(blank=True, to='entries.SpecificNeedsGroup'),
        ),
        migrations.AddField(
            model_name='entry',
            name='vulnerable_groups',
            field=models.ManyToManyField(blank=True, to='entries.VulnerableGroup'),
        ),
    ]
