# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-06 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('entries', '0002_auto_20161106_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.AffectedGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EntryInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerpt', models.TextField(blank=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InformationAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InformationPillar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contains_sectors', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InformationSubpillar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.InformationPillar')),
            ],
        ),
        migrations.CreateModel(
            name='Reliability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificNeedsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Subsector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='VulnerableGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='informationattribute',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Sector'),
        ),
        migrations.AddField(
            model_name='informationattribute',
            name='subpillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.InformationSubpillar'),
        ),
        migrations.AddField(
            model_name='informationattribute',
            name='subsector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Subsector'),
        ),
        migrations.AddField(
            model_name='entryinformation',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='entries.InformationAttribute'),
        ),
        migrations.AddField(
            model_name='entryinformation',
            name='reliability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Reliability'),
        ),
        migrations.AddField(
            model_name='entryinformation',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Severity'),
        ),
        migrations.AddField(
            model_name='entry',
            name='informations',
            field=models.ManyToManyField(blank=True, to='entries.EntryInformation'),
        ),
        migrations.AddField(
            model_name='entry',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Lead'),
        ),
    ]
