# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-10 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20161108_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reliability',
            options={'verbose_name_plural': 'Reliabilities'},
        ),
        migrations.AlterModelOptions(
            name='severity',
            options={'verbose_name_plural': 'Severities'},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='informations',
        ),
        migrations.AddField(
            model_name='entryinformation',
            name='entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='entries.Entry'),
            preserve_default=False,
        ),
    ]
