# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20160803_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.Sector'),
        ),
        migrations.AddField(
            model_name='sector',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
