# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20160515_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crisisdriver',
            name='id',
        ),
        migrations.AlterField(
            model_name='crisisdriver',
            name='name',
            field=models.CharField(max_length=70, primary_key=True, serialize=False),
        ),
    ]
