# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20161110_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.RemoveField(
            model_name='entryinformation',
            name='attributes',
        ),
        migrations.AddField(
            model_name='informationattribute',
            name='information',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='entries.EntryInformation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informationattribute',
            name='subsector',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.Subsector'),
        ),
    ]
