# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_auto_20161002_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='entries.Sector'),
        ),
    ]
