# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_auto_20160515_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=70)),
                ('property_name', models.CharField(max_length=70)),
                ('geojson', models.FileField(upload_to='adminlevels/')),
            ],
            options={
                'ordering': ['country', 'level'],
            },
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AddField(
            model_name='adminlevel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Country'),
        ),
        migrations.AlterUniqueTogether(
            name='adminlevel',
            unique_together=set([('country', 'level')]),
        ),
    ]
