# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_entry_sectors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationattributegroup',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='informationattributegroup',
            name='color',
            field=models.CharField(default='#f0f0f0', max_length=20),
        ),
        migrations.AddField(
            model_name='informationattributegroup',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='informationattributegroup',
            name='selected_color',
            field=models.CharField(default='#008080', max_length=20),
        ),
        migrations.AddField(
            model_name='informationattributegroup',
            name='selected_text_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='informationattributegroup',
            name='text_color',
            field=models.CharField(default='#414141', max_length=20),
        ),
    ]
