# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20160626_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectedgroupdata',
            name='affected_group',
        ),
        migrations.RemoveField(
            model_name='affectedgroupdata',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='vulnerablegroupdata',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='vulnerablegroupdata',
            name='vulnerable_group',
        ),
        migrations.RenameField(
            model_name='affectedgroup',
            old_name='group_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='affectedgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.AffectedGroup'),
        ),
        migrations.AddField(
            model_name='entry',
            name='affected_groups',
            field=models.ManyToManyField(blank=True, to='entries.AffectedGroup'),
        ),
        migrations.DeleteModel(
            name='AffectedGroupData',
        ),
        migrations.DeleteModel(
            name='VulnerableGroup',
        ),
        migrations.DeleteModel(
            name='VulnerableGroupData',
        ),
    ]
