# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20161110_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryinformation',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
