# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-08 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_auto_20161006_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
