# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_auto_20160704_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLevelSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_name', models.CharField(max_length=150)),
                ('admin_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.AdminLevel')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='map_selections',
            field=models.ManyToManyField(blank=True, to='entries.AdminLevelSelection'),
        ),
    ]
