# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlevel',
            name='property_pcode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
