# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_auto_20160704_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='tags',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
