# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_auto_20161111_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='created_by',
            new_name='modified_by',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='created_at',
        ),
        migrations.AddField(
            model_name='entry',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
