# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_auto_20161111_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationattribute',
            name='subsectors',
            field=models.ManyToManyField(blank=True, related_name='subsectors', to='entries.Subsector'),
        ),
        migrations.AlterField(
            model_name='informationattribute',
            name='subsector',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsector', to='entries.Subsector'),
        ),
    ]
