# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-15 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_adminlevel_property_pcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlevelselection',
            name='pcode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
