# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_sector_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='tags',
            new_name='tags_json',
        ),
    ]
