# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 11:14
from __future__ import unicode_literals

from django.db import migrations


def make_many_subsectors(apps, schema_editor):
    InformationAttribute = apps.get_model('entries', 'InformationAttribute')
    for attr in InformationAttribute.objects.all():
        if attr.subsector:
            attr.subsectors.add(attr.subsector)


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0012_auto_20161116_1114'),
    ]

    operations = [
        migrations.RunPython(make_many_subsectors)
    ]
