# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0013_auto_20161116_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationattribute',
            name='subsector',
        ),
    ]
