# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0013_auto_20161116_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reliability',
            options={'ordering': ['level'], 'verbose_name_plural': 'Reliabilities'},
        ),
        migrations.AlterModelOptions(
            name='severity',
            options={'ordering': ['level'], 'verbose_name_plural': 'Severities'},
        ),
        migrations.AddField(
            model_name='informationpillar',
            name='appear_in',
            field=models.CharField(blank=True, choices=[('PIN', 'People in need'), ('HAC', 'Humanitarian access'), ('HPR', 'Humanitarian profile')], default=None, max_length=3, null=True),
        ),
    ]
