# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_auto_20160712_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlevelselection',
            name='admin_level',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='affected_groups',
        ),
        migrations.AddField(
            model_name='entry',
            name='affected_groups',
            field=models.TextField(default='[]'),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='map_selections',
        ),
        migrations.AddField(
            model_name='entry',
            name='map_selections',
            field=models.TextField(default='[]'),
        ),
        migrations.DeleteModel(
            name='AdminLevelSelection',
        ),
    ]
