# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 12:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0015_auto_20160712_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLevelSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('admin_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.AdminLevel')),
            ],
        ),
        migrations.DeleteModel(
            name='CrisisDriver',
        ),
        migrations.DeleteModel(
            name='UnderlyingFactor',
        ),
        migrations.AlterModelOptions(
            name='informationattributegroup',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='affected_groups',
        ),
        migrations.AddField(
            model_name='entry',
            name='affected_groups',
            field=models.ManyToManyField(blank=True, to='entries.AffectedGroup'),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='map_selections',
        ),
        migrations.AddField(
            model_name='entry',
            name='map_selections',
            field=models.ManyToManyField(blank=True, to='entries.AdminLevelSelection'),
        ),
        migrations.AlterUniqueTogether(
            name='adminlevelselection',
            unique_together=set([('admin_level', 'name')]),
        ),
    ]
