# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0015_sector_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationattribute',
            name='subsector',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informationattribute_donot_use', to='entries.Subsector', verbose_name='DO NOT USE'),
        ),
        migrations.AlterField(
            model_name='informationattribute',
            name='subsectors',
            field=models.ManyToManyField(blank=True, to='entries.Subsector'),
        ),
    ]
