# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0016_auto_20161209_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlevel',
            name='geojson',
            field=models.FileField(blank=True, default=None, null=True, upload_to='adminlevels/'),
        ),
    ]
