# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0018_auto_20170108_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='best_of_bullshits',
            field=models.TextField(blank=True, default=''),
        ),
    ]
