# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0019_entry_best_of_bullshits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='best_of_bullshits',
        ),
        migrations.AddField(
            model_name='informationattribute',
            name='bob',
            field=models.BooleanField(default=False),
        ),
    ]
