# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0020_auto_20170217_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationattribute',
            name='bob',
        ),
        migrations.AddField(
            model_name='entryinformation',
            name='bob',
            field=models.BooleanField(default=False),
        ),
    ]
