# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0021_auto_20170217_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='entry_images/')),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.EntryInformation')),
            ],
        ),
    ]
