# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 06:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def migrate_created(apps, schema_editor):
    Entry = apps.get_model('entries', 'Entry')
    for entry in Entry.objects.all():
        entry.created_at = entry.modified_at
        entry.created_by = entry.modified_by
        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0021_auto_20170217_0429'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='entry',
        #     name='created_at',
        #     field=models.DateTimeField(default=django.utils.timezone.now),
        # ),
        # migrations.AddField(
        #     model_name='entry',
        #     name='created_by',
        #     field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries_created', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AlterField(
        #     model_name='entry',
        #     name='modified_by',
        #     field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        migrations.RunPython(migrate_created),
    ]
