# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0022_auto_20170305_0653'),
        ('entries', '0022_entryimage'),
    ]

    operations = [
    ]
