# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0028_remove_informationpillar_shown_in_default_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('elements', models.TextField(default='{}')),
            ],
        ),
        migrations.AddField(
            model_name='entryinformation',
            name='elements',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='entryinformation',
            name='template',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.EntryTemplate'),
        ),
    ]
