# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0031_auto_20170324_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryinformation',
            name='reliability',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.Reliability'),
        ),
        migrations.AlterField(
            model_name='entryinformation',
            name='severity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.Severity'),
        ),
    ]
