# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0032_auto_20170331_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryinformation',
            name='template',
        ),
        migrations.AddField(
            model_name='entry',
            name='template',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.EntryTemplate'),
        ),
    ]
