# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0035_auto_20170405_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
