# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0037_exporttoken_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttoken',
            name='export_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='export_temp/'),
        ),
    ]
