# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0038_exporttoken_export_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporttoken',
            name='export_file',
        ),
    ]
