# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0039_remove_exporttoken_export_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrytemplate',
            name='snapshot_pageone',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='entrytemplate',
            name='snapshot_pagetwo',
            field=models.TextField(default=None, null=True),
        ),
    ]
