# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0040_auto_20170519_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryinformation',
            name='elements',
            field=models.TextField(default='[]'),
        ),
    ]
