# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 07:44
from __future__ import unicode_literals

from django.db import migrations


def fix_elements(apps, schema_editor):
    EntryInformation = apps.get_model('entries', 'EntryInformation')
    for info in EntryInformation.objects.all():
        if info.elements == '{}':
            info.elements = '[]'
            info.save()


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0041_auto_20170606_0744'),
    ]

    operations = [
        migrations.RunPython(fix_elements),
    ]
