# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-06 09:05
from __future__ import unicode_literals

from django.db import migrations


def remove_origin_from_entry_images(apps, schema_editor):
    EntryInformation = apps.get_model('entries', 'EntryInformation')
    for info in EntryInformation.objects.all():
        if info.image.startswith('http://thedeep.io/'):
            info.image = info.image.replace('http://thedeep.io/', '')
            info.save()

        if info.image.startswith('http://54.83.82.134'):
            info.image = info.image.replace('http://54.83.82.134', '')
            info.save()


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0042_auto_20170606_0744'),
    ]

    operations = [
        migrations.RunPython(remove_origin_from_entry_images),
    ]
