# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-30 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0044_auto_20170809_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlevel',
            name='geo_areas',
            field=models.TextField(default='[]'),
        ),
    ]
