# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0023_country_key_figures_data_migrations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='group-avatar/')),
                ('description', models.TextField(blank=True)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(to='leads.Event')),
            ],
        ),
    ]
