# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usergroup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='slug',
            field=models.SlugField(default=None, editable=False),
            preserve_default=False,
        ),
    ]
