# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usergroup', '0002_usergroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='projects',
            field=models.ManyToManyField(blank=True, to='leads.Event'),
        ),
    ]
