# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 06:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usergroup', '0003_auto_20170217_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='admins',
            field=models.ManyToManyField(related_name='groups_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
