# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 05:20
from __future__ import unicode_literals

from django.db import migrations


def transfer_ownership(apps, schema_editor):
    UserGroup = apps.get_model("usergroup", "UserGroup")
    for usergroup in UserGroup.objects.all():
        if usergroup.admins.count() > 0:
            usergroup.owner = usergroup.admins.all()[0]
            usergroup.save()


class Migration(migrations.Migration):

    dependencies = [
        ('usergroup', '0006_usergroup_owner'),
    ]

    operations = [
        migrations.RunPython(transfer_ownership),
    ]
