# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0030_auto_20170324_0555'),
        ('usergroup', '0007_auto_20170226_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='entry_tempates',
            field=models.ManyToManyField(blank=True, to='entries.EntryTemplate'),
        ),
    ]
