# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usergroup', '0008_usergroup_entry_tempates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='entry_tempates',
            new_name='entry_templates',
        ),
    ]
