# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usergroup', '0009_auto_20170324_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='acaps',
            field=models.BooleanField(default=False),
        ),
    ]
