# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-02 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usergroup', '0010_usergroup_acaps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='acaps',
            field=models.BooleanField(default=False, verbose_name='Global crisis monitoring'),
        ),
    ]
